apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: inspection-zone
spec:
  selector:
    app: classifier
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
