apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: inspection-zone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox:latest
          command: ["sh", "-c", "until nc -z zookeeper 2181; do echo waiting; sleep 2; done;"]
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.4.0
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-svc:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            # -----------------------------------------------
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms512M -Xmx512M"
          ports:
            - containerPort: 9092
              name: broker
