apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    app: modifier
  name: modifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modifier
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        app: modifier
    spec:
      containers:
        - image: modifier:latest
          imagePullPolicy: Never
          name: modifier
          ports:
            - containerPort: 8080
      restartPolicy: Always