apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: simulator
  name: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: simulator
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: simulator
    spec:
      containers:
        - image: simulator:latest
          imagePullPolicy: Never
          name: simulator
          ports:
            - containerPort: 8080   # <-- port interne du container
      restartPolicy: Always