apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: verifier
  name: verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: verifier
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: verifier
    spec:
      containers:
        - image: verifier:latest
          imagePullPolicy: Never
          name: verifier
          ports:
            - containerPort: 8080
      restartPolicy: Always