apiVersion: apps/v1
kind: Deployment
metadata:
  name: modifier
  namespace: inspection-zone
  labels:
    app: modifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modifier
  template:
    metadata:
      labels:
        app: modifier
    spec:
      containers:
        - name: modifier
          image: modifier:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # Connexion au nouveau nom du service Kafka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-svc.inspection-zone.svc.cluster.local:9092"
