apiVersion: v1
kind: Service
metadata:
  name: simulator
  namespace: inspection-zone
spec:
  selector:
    app: simulator
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
